import { Lora, Rethink_Sans } from "next/font/google";
import './globals.css';
import RootLayout from './components/RootLayout';

const lora = Lora({ subsets: ['latin'] });
const rethinkSans = Rethink_Sans({
  subsets: ['latin']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function Layout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${rethinkSans.className} antialiased`}
      >
        <RootLayout children={children} />
      </body>
    </html>
  );
}
